#!/usr/bin/env ruby

# Small script for i3status using ACPI

stat = `acpi -ab`

cs = (stat.scan /Discharging|Charging|Charged/)[0]

cs = case cs
  when 'Discharging'
    '⇩'
  when 'Charging'
    '⇧'
  when 'Charged'
    '⇗'
  else
    '?'
end

cr = (stat.scan /\d{1,3}%/)[0]

ct = (stat.scan /\d\d:\d\d:\d\d/)[0]

ac = (stat.scan /on-line|off-line/)[0]

ac = case ac
  when 'on-line'
    "\u{1F50C}"
  when 'off-line'
    "\u{1F50B}"
  else
    '?'
end

puts "#{ac}#{cs} #{cr} #{ct}"
